name: docker
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run hello-world   ← skridt 1: hele filen
      - run: bash container.sh        ← skridt 2 tilføjer denne linje
